compile:
	../ei-daemon-fw/bin/arduino-cli compile --fqbn arduino:mbed_nano:nano33ble --log --output-dir artifacts --export-binaries

upload:
	../ei-daemon-fw/bin/arduino-cli upload --fqbn arduino:mbed_nano:nano33ble -p /dev/serial/by-id/usb-Arduino_Arduino_Nano_33_BLE_00000000000000003C48BB3E0BD44A03-if00
